#!/bin/bash
# ───────────────────────────────────────────────────────────────────
#  install-icons.sh — Windows Modern v2 icon pack
# ───────────────────────────────────────────────────────────────────
source "$(dirname "$0")/install-lib.sh"

# v2 output directory (context-based, 4,947 icons)
V2_SRC="$SRC_DIR/icons_v2/output/windows-modern-v2"

if [ ! -d "$V2_SRC" ]; then
    warn "Icon pack v2 not found at $V2_SRC"
    warn "Make sure icons_v2/output/windows-modern-v2/ exists."
    warn "(It is built from icons_v2/sources/ using the selection pipeline.)"
    exit 1
fi

THEME_NAME="windows-modern-v2"
THEME_DIR="$ICONS_DIR/$THEME_NAME"

# Apply tracked v2 icon overrides (cleaned/custom icons not generated by the pipeline)
OVERRIDES_DIR="$SRC_DIR/overrides/icons-v2"
if [ -d "$OVERRIDES_DIR" ]; then
    step "Applying v2 icon overrides"
    cp -r "$OVERRIDES_DIR"/. "$V2_SRC"/
fi

info "Installing icon pack v2..."
step "Removing old installation"
rm -rf "$THEME_DIR"

step "Copying $THEME_NAME"
ensure_dir "$ICONS_DIR"
cp -r "$V2_SRC" "$THEME_DIR"

if command -v gtk-update-icon-cache &>/dev/null; then
    gtk-update-icon-cache -f "$THEME_DIR" &>/dev/null || true
fi

info "Icons installed ($THEME_NAME)"

# ── Apply icon theme instantly (same as System Settings) ───────────
if command -v kwriteconfig6 &>/dev/null; then
    step "Applying icon theme ($THEME_NAME)"
    # Plasma 6 stores the theme in kcmicons; kdeglobals is the legacy fallback
    kwriteconfig6 --file kdeglobals --group Icons --key Theme "$THEME_NAME"
    kwriteconfig6 --file kcmicons --group Icons --key Theme "$THEME_NAME"

    if command -v kbuildsycoca6 &>/dev/null; then
        step "Refreshing KDE icon cache"
        kbuildsycoca6 --noincremental &>/dev/null || true
    fi
else
    warn "kwriteconfig6 not found — icon theme installed but not activated."
    warn "Set it manually in System Settings > Appearance > Icons."
fi
